### ISSUE TITLE
How do I processes messages in parallel?

### ISSUE THREAD

**Issue by tandrup** [nodefluent/kafka-connect#10]
I have a Kafka topic that is partitioned into 32 partitions.

I've tried to write a simple sink to call an REST API once per Kafka message.

But it seems like it's processing my Kafka messages in sequence.

I've set `maxTasks: 32` in my config, without any result.

How can I make it either process *n* partitions in parallel. And/or process multiple messages from each partition? It seems the `put` method gets an array, but for me it's always an array of one element.

**Comment by krystianity** [comment]
Hi Mads,

processing the messages 1 by 1 and awaiting a non error callback before commit is actually the implemented default behavior if you are using the new native consumer API. This ensures 100% sinking rate. We simply handle more load by scaling our kubernetes pods with this solution.

However, when you are using the old javascript kafka client (by setting the `kafka` object in your config and not the `noptions` object [checkout the [sinek](https://github.com/nodefluent/node-sinek) module for more info on this]), which you are probably doing, you can control the amount of parallel executions by tuning the `workerPerPartition` config parameter, it is set to 1 per default. 
e.g.:
```
const config = {
 kafka: {
  workerPerPartition: 32
 }
};
```

The maxTasks parameter is actually just something I have ported from the JAVA API, it is passed to the taskConfig call of the Connector class, you would have to implement your own logic in our inherited connector to actually do something with this value.

Again.. I suggest switching to the native client by setting `noptions` instead of `kafka` [instructions here](https://github.com/nodefluent/node-sinek/blob/master/lib/librdkafka/README.md), make sure to check the memory parameters step. And scaling to multiple instances - you can configure these processes to consume as little as 50 MB memory and spawn tons of them in parallel..obviously you would only be able to scale to the maximum number of partitions with this ;)

C

**Comment by tandrup** [comment]
Thanks for the quick and detailed response. It helped me better understanding how you envisioned scaling.

I'll switched to the native client. It also seems like the javascript Kafka client didn't properly commit the offset back to Kafka. With the native client it works.

Thanks for the help!
